baseURL = "https://andy840119.github.io/"
defaultContentLanguage = "zh-tw" # Default language to use (if you setup multilingual)
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.
title = "他喵的野生日常"
theme = "hugo-theme-hello-friend"

rssLimit = 0

googleAnalytics = "UA-164533327-1"
Copyright = "Copyright &copy; 2019-2020 他喵的野生日常. Distributed by an <a href=\"https://github.com/andy840119\">GPL V3 license.</a>"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
