# theme
remote_theme: andy840119/tameowder-theme

# header
title: 他喵的又在搞飛機了..=ω=a
description: 他喵的野生日常，Github分部
baseurl: "/"
url: "https://andy840119.github.io"


# Aux links for the upper right navigation
aux_links:
  "my GitHub":
    - "//github.com/andy840119/"

# navigation
facebook_url: https://www.facebook.com/OAQaa

# trackng
google_analytics: UA-164533327-1

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019-2020 他喵的野生日常. Distributed by an <a href=\"https://github.com/andy840119\">GPL V3 license.</a>"
